name: "Setup Cairo Native Dependencies"
description: "Sets up LLVM and GMP libraries"

runs:
  using: "composite"
  steps:
    - name: Make script executable
      shell: bash
      run: chmod +x ./scripts/setup_native_deps.sh

    - name: Install Cairo Native Runtime Dependencies
      id: set-runtime-deps
      shell: bash
      run: |
        sudo ./scripts/setup_native_deps.sh

    - name: Set Environment Variables
      id: set-env-vars
      shell: bash
      run: |
        echo "MLIR_SYS_190_PREFIX=/usr/lib/llvm-19/" >> $GITHUB_ENV &&
        echo "LLVM_SYS_191_PREFIX=/usr/lib/llvm-19/" >> $GITHUB_ENV &&
        echo "TABLEGEN_190_PREFIX=/usr/lib/llvm-19/" >> $GITHUB_ENV